part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const ONBOARDING = _Paths.ONBOARDING;
  static const ONBOARDING2 = _Paths.ONBOARDING2;
  static const ONBOARDING3 = _Paths.ONBOARDING3;
  static const ROLE = _Paths.ROLE;
  static const SIGNUP = _Paths.SIGNUP;
  static const OTP = _Paths.OTP;
  static const SPLASH = _Paths.SPLASH;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const SIGN_IN = _Paths.SIGN_IN;
  static const HOME = _Paths.HOME;
  static const SERVICE = _Paths.SERVICE;
  static const MECHANIC = _Paths.MECHANIC;
  static const ACCOUNT = _Paths.ACCOUNT;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const MY_LOCATION_SELECTION = _Paths.MY_LOCATION_SELECTION;
  static const MAP = _Paths.MAP;
  static const ORDERTRACKING = _Paths.ORDERTRACKING;
  static const MECHANICDETAILS = _Paths.MECHANICDETAILS;
  static const RATINGANDREVIEW = _Paths.RATINGANDREVIEW;
  static const CHECK_OUT = _Paths.CHECK_OUT;
  static const CHECK_OUT_SIGNUP = _Paths.CHECK_OUT_SIGNUP;
  static const MYINFO = _Paths.MYINFO;
  static const PREVIOUSBOOKING = _Paths.PREVIOUSBOOKING;
  static const FAQ = _Paths.FAQ;
  static const FAVOURITE = _Paths.FAVOURITE;
  static const ABOUTUS = _Paths.ABOUTUS;
  static const MYVEHECLE = _Paths.MYVEHECLE;
  static const ADDVEHICLE = _Paths.ADDVEHICLE;
  static const MESSAGEINBOX = _Paths.MESSAGEINBOX;
  static const MECHANIC_HOME = _Paths.MECHANIC_HOME;
  static const MAP_SERVICE_AREA = _Paths.MAP_SERVICE_AREA;
  static const MECHANIC_ORDER = _Paths.MECHANIC_ORDER;
  static const ORDER_DETAILS = _Paths.ORDER_DETAILS;
  static const MECHANIC_MAP = _Paths.MECHANIC_MAP;
  static const MECHANIC_PAYMENT = _Paths.MECHANIC_PAYMENT;
  static const MECHANIC_PROFILE = _Paths.MECHANIC_PROFILE;
  static const MY_SERRVICE = _Paths.MY_SERRVICE;
  static const MECHANIC_SERVICE = _Paths.MECHANIC_SERVICE;
  static const MECHANIC_ADD_PAYMENT = _Paths.MECHANIC_ADD_PAYMENT;
  static const MECHANIC_PAYMENT_METHOD = _Paths.MECHANIC_PAYMENT_METHOD;
}

abstract class _Paths {
  _Paths._();
  static const ONBOARDING = '/onboarding1';
  static const ONBOARDING2 = '/onboarding2';
  static const ONBOARDING3 = '/onboarding3';
  static const ROLE = '/role';
  static const SIGNUP = '/signup';
  static const OTP = '/otp';
  static const SPLASH = '/splash';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const CHANGE_PASSWORD = '/change-password';
  static const SIGN_IN = '/sign-in';
  static const HOME = '/home';
  static const SERVICE = '/service';
  static const MECHANIC = '/mechanic';
  static const ACCOUNT = '/account';
  static const NOTIFICATION = '/notification';
  static const MY_LOCATION_SELECTION = '/my-location-selection';
  static const MAP = '/map-view';
  static const ORDERTRACKING = '/order-tracking';
  static const MECHANICDETAILS = '/mechanic_details';
  static const RATINGANDREVIEW = '/rating_and_review';
  static const CHECK_OUT = '/check-out';
  static const CHECK_OUT_SIGNUP = '/check-out-signup';
  static const MYINFO = '/my-info';
  static const PREVIOUSBOOKING = '/previous-booking';
  static const FAQ = '/faq';
  static const FAVOURITE = '/favourite';
  static const ABOUTUS = '/about-us';
  static const MYVEHECLE = '/my-vehicle';
  static const ADDVEHICLE = '/add-vehicle';
  static const MESSAGEINBOX = '/message-inbox';
  static const MECHANIC_HOME = '/mechanic-home';
  static const MAP_SERVICE_AREA = '/map-service-area';
  static const MECHANIC_ORDER = '/mechanic-order';
  static const ORDER_DETAILS = '/order-detail';
  static const MECHANIC_MAP = '/mechanic-map';
  static const MECHANIC_PAYMENT = '/mechanic-payment';
  static const MECHANIC_PROFILE = '/mechanic-profile';
  static const MY_SERRVICE = '/my-serrvice';
  static const MECHANIC_SERVICE = '/mechanic-service';
  static const MECHANIC_ADD_PAYMENT = '/mechanic-add-payment-info';
  static const MECHANIC_PAYMENT_METHOD = '/mechanic-payment-method';
}
